print("task1")
from math import sqrt, ceil, floor, cos, sin, exp, log, pow, pi, e, inf
print(f"square root function :(sqrt(20))")
print("squar root function:",sqrt(20))
print(f"ceil function :(ceil(45.05))")
print(f"floor functon :(floor(45.05))")
print(f"factorial function :(factorial(5))")
print(f"sin of (45) is (sin(45))")
print(f"cos of 90 is (cos(90))")
print("Exp of 20.3 is", exp(20.3))
print("log of 19.25 is", log(19.25))
print("4 to the power 3 is" ,pow(4,3))
print(f"Value of pi is (pi), e (e) and infinity is (inf)")